Handle interruptions in mini games-bugFix
systers/powerup-android pull request #1158
Opened 2018-06-05 08:24 UTC by aayushinigam

### Description
Handles interruptions in mini games 
1. Keeps next scenario unlocked if back is pressed while playing.
2. Stop background music if back is pressed.

BONUS : After all the scenarios are completed - clicking on any scenario opened only the Library one, but now clicking on any scenario opens the respective scenario.

Fixes #777

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
It has been run successfully on an android device.
![20180604_234433](https://user-images.githubusercontent.com/24635221/40934491-968ae02c-6852-11e8-9b87-3e2bc121a447.gif)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] New and existing unit tests pass locally with my changes

2018-06-05 10:08 UTC, aayushinigam commented
@Rimjhim28  I made the changes suggested by you. Git rebasing is giving me a hard time - I did something and it led to deletion of all changes in last PR and it got closed automatically. I apologise.

2018-06-26 01:28 UTC, asclepiusgal commented
@ExactlyMay do you recommend we move this to product backlog until GSoC concludes?

2018-08-12 18:31 UTC, Rimjhim28 requested changes
@aayushinigam Please fix the travis error.

2018-08-12 18:33 UTC, aayushinigam commented
I thought this will be closed since it's based on old database architecture. Hence I didn't resolve those errors. Should I?

2018-08-12 18:36 UTC, Rimjhim28 commented
Yes @aayushinigam! I missed on that.
I am closing the PR for now. You can send a new one after all of GSoC work is merged to develop (probably in a day or two). Meanwhile, I am making some new issues available. If you have time, you can work on them.

2018-08-12 18:36 UTC, closed without merging