fixed hardcoded text lint error #1102
systers/powerup-android pull request #1321
Opened 2019-01-21 12:45 UTC by hsymphonyk

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2019-01-26 14:57 UTC, Rimjhim28 requested changes

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <string name="zero">0</string>
Reuse txt_zero instead of creating a new string resource.

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <string name="_0">0</string>
Reuse ```txt_zero``` instead of creating a new string resource.

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <!--<string name="_0">0</string>-->
Remove the commented out string resources since they are not used,

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <string name="_skin">Skin</string>
remove the uderscore

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <!--<string name="_0">0</string>-->
Remove all the commented out string resources.

2019-01-26 14:57 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/values/strings.xml
> +    <string name="this_is_your_final_avatar_press_continue_to_start_your_journey">This is your final avatar! Press continue to start your Journey...</string>
The name is too long. Use something short and appropriate.
Could be something like ```final_avatar_message```.

2019-01-26 14:58 UTC, Rimjhim28 reviewed
Please go through contribution guidelines and submit a pull request only after you are assigned to an issue.

2019-01-28 12:31 UTC, Rimjhim28 requested changes
@hsymphonyk Travis build is failing. Please fix it.
Also, squash the commits.

2019-01-28 16:25 UTC, hsymphonyk commented
Hello, @Rimjhim28 , I have done the changes requested. Please review this.Thank you.

2019-01-31 13:27 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/layout-land/avatar_room.xml
>                  android:textSize="@dimen/selection_text_size" />
Remove the underscore.

2019-01-31 13:29 UTC, Rimjhim28 commented on PowerUp/app/src/main/res/layout/store_selection_view.xml
> +        android:text="@string/_5"
change this to ```str_5```

2019-01-31 13:29 UTC, Rimjhim28 requested changes
I have added some comments. Be sure that you squash the commits at the end.

2019-02-18 06:37 UTC, hsymphonyk commented
Hello @Rimjhim28 , I have made the requested changes. Please review them.

2019-02-20 13:01 UTC, hsymphonyk commented
@Rimjhim28 I have squashed the commits. Please review.

2019-02-21 09:27 UTC, Rimjhim28 approved these changes
Good Job @hsymphonyk! :tada:

2019-02-21 09:27 UTC, merged