fixed issue #1325
systers/powerup-android pull request #1332
Opened 2019-01-28 19:43 UTC by apoorva-mk

### Description
Fixed the cause of timer stopping when home button pressed and game resumed by adding onRestart() method.

Fixes # 1325

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested it on various possible scenarios and the app performed as expected.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2019-01-31 15:17 UTC, Rimjhim28 requested changes
@apoorva-mk The changes look good. Please rename the ```Restart``` variable to ```restart```. We follow camelcases for naming variables.

2019-01-31 15:18 UTC, Rimjhim28 commented on PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
> +    //Variable to see if
The comment here looks incomplete

2019-01-31 15:19 UTC, Rimjhim28 commented on PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
> +    {
follow proper parenthesis pattern.
it should have been:
```public void onRestart() {
.........................
} ```

2019-01-31 15:20 UTC, Rimjhim28 requested changes
Use an appropriate commit message.

2019-02-02 18:01 UTC, apoorva-mk commented
Hey I've made the suggested changes! Please review it, thank you :)

2019-02-09 16:12 UTC, Rimjhim28 requested changes
@apoorva-mk Squash the commits.

2019-02-22 05:06 UTC, closed without merging