Placed google repository as first priority.
systers/powerup-android pull request #1338
Opened 2019-01-30 08:45 UTC by moksh-mahajan

### Description
Updated build.gradle file to make google repository as first priority.

Fixes #1336 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Application was built successfully in android studio without any errors

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2019-01-30 08:52 UTC, moksh-mahajan commented
@Rimjhim28 Please review.

2019-01-30 18:55 UTC, Rimjhim28 commented on PowerUp/build.gradle
>      }
Please remove this extra line.

2019-01-30 19:29 UTC, moksh-mahajan commented on PowerUp/build.gradle
>      }
Done. Please check.

2019-01-31 13:19 UTC, Rimjhim28 requested changes
@moksh-mahajan Squash the commits.

2019-01-31 16:57 UTC, moksh-mahajan commented
@Rimjhim28 Done. Please review.

2019-02-09 16:15 UTC, Rimjhim28 approved these changes
LGTM

2019-02-09 16:15 UTC, merged