feat: Contact section added on README
systers/powerup-android pull request #1383
Opened 2020-03-09 19:34 UTC by Mehulipal

### Description
Contributors need to know where they can reach out to the community, so that they can discuss or see discussions of this project. Hence, contact section has been added on README.

Fixes #1377 

### Type of Change:

- Documentation
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

![Screenshot (180)](https://user-images.githubusercontent.com/54908756/76249474-67c0d400-6269-11ea-87ca-1d7cb5c1d980.png)

### Checklist:

&#9745;  My PR follows the style guidelines of this project
&#9745;  I have made corresponding changes to the documentation
&#9745;  My changes generate no new warnings 
&#9745;  New and existing unit tests pass locally with my changes

2020-03-09 19:36 UTC, Mehulipal commented
Please review.

2020-03-09 19:46 UTC, isabelcosta requested changes
@Mehulipal thank you so much for this contribution!
I left a small change request that I think could improve and make the message more clear :)
Once this is done, I am more than happy to approve.

2020-03-09 19:46 UTC, isabelcosta commented on README.md
> +If you are interested in contributing to the PowerUp application, we have a dedicated stream for this project where you can ask questions and interact with the community. Join with us on Zulip [here]
```suggestion
If you are interested in contributing to the PowerUp application, we have a dedicated stream for this project where you can ask questions and interact with the community. Join with us on [#powerup](https://anitab-org.zulipchat.com/#narrow/stream/222537-powerup) stream on Zulip.
```

2020-03-09 20:25 UTC, Mehulipal commented
Ma'am, I have made the requested changes. Please review.

2020-03-09 20:37 UTC, isabelcosta approved these changes
Great work @Mehulipal 🎉

2020-03-09 20:39 UTC, isabelcosta commented
@mayburgos can you approve/review this as well, since this is a small change to the readme?

2020-03-11 13:48 UTC, Mehulipal commented
@mayburgos  kindly review the changes

2020-03-11 17:31 UTC, sunjunkie approved these changes

2020-03-12 19:14 UTC, atm1504 commented
@Mehulipal the branch name you used has no connection with the issue you resolved, please prefer to use a proper branch name. You should try to follow such guidelines to work and maintain a large project.
Moreover, the title of the pr should start with```chore``` not ```feat```.

2020-03-14 09:39 UTC, Mehulipal commented
@atm1504 I have made the requested changes in PR name. I will surely keep your advice in mind and will name my branch accordingly from next time. Thanks for your review :)

2020-03-14 10:36 UTC, isabelcosta commented
great work @Mehulipal 🎉

2020-03-14 10:37 UTC, merged